/**
 * @param entityId the entity ID to generate a row ID for
 * @return पंक्ति आईडी (row ID)
 */
public String id(String entityId) {
    // Assuming the row ID is generated by appending a prefix to the entity ID
    return "ROW_" + entityId;
}