from py4j.java_gateway import JavaGateway
import pandas as pd
import os
from javaparser import *

# Supported natural languages for code generation analysis
languages = ['italian', 'hindi', 'chinese', 'english', 'spanish']

# Programming language to analyze
prog_lang = 'java'

# Model used for code generation
models = ['deepseek', 'gpt', 'claude']

# Number of iterations for code analysis
number_of_iteration = 10

def extractMethod(source_code, method, id):
    """
    Extracts a specific method from the provided Java source code using the JavaParser.

    Parameters:
    - source_code (str): The Java source code from which to extract the method.
    - method (str): The method signature to identify the method.
    - id (int): A unique identifier for the method extraction.

    Returns:
    - str: The extracted method code or 'ERROR' if extraction fails.
    """
    gateway = JavaGateway()
    java_parser_server = gateway.entry_point  # Entry point to your Java parser

    client = JavaParserClient(gateway, java_parser_server)

    return client.getMethodCode(source_code, method, id)

def main():
    """
    Main function to process Java code generated by different models and languages.

    For each language and iteration, it reads the generated code, extracts relevant methods,
    and stores the processed data in a JSONL file for further analysis.

    The function performs the following steps:
    1. Reads the main CSV file containing original data.
    2. Iterates through generated code across multiple iterations.
    3. Extracts methods using the JavaParser if applicable.
    4. Stores the results in a JSONL output file.

    Output:
    - A JSONL file with the extracted method code for each language and iteration.

    Requirements:
    - JavaParser server must be running to extract methods from the generated Java code.
    """
    for model in models:
        for language in languages:
            main_file = f'./Data/{prog_lang}_{language}.csv'
            main_df = pd.read_csv(main_file)

            if 'id' in main_df.columns:
                main_df.rename(columns={'id': '_id'}, inplace=True)

            # Initialize a map to store extracted methods
            code_map = {row['_id']: [] for _, row in main_df.iterrows()}

            csv_path = f'./Data/generation/{prog_lang}_{language}_{model}'

            for iteration in range(number_of_iteration):
                print(f"Analyzing {prog_lang} with {model} for {language} for iteration {iteration}")
                read_csv_path = os.path.join(csv_path, f'iter_{iteration}', f'{prog_lang}_{language}_{model}.csv')

                df = pd.read_csv(read_csv_path)
                if 'id' in df.columns:
                    df.rename(columns={'id': '_id'}, inplace=True)

                # Process each row to extract methods
                for _, row in df.iterrows():
                    if row['_id'] in code_map:
                        starting_code = row['code']
                        template = f"public class Template {{\n{starting_code}\n}}"
                        generated_code = row['generated_code']

                        # Extract method if available, otherwise use the entire generated code
                        if 'class' not in generated_code:
                            method_code = generated_code
                        else:
                            method_code = extractMethod(generated_code, template, row['_id'])
                            if method_code == 'ERROR':
                                method_code = generated_code

                        code_map[row['_id']].append(method_code)

            # Save the extracted methods to a JSONL file
            output_df = pd.DataFrame({
                '_id': list(code_map.keys()),
                'generate_results': list(code_map.values())
            })

            output_df.to_json(f'./Data/tests/{prog_lang}_{language}_{model}.jsonl', orient='records', lines=True)

if __name__ == '__main__':
    main()
